language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
  - export CC=gcc-9
  - export CXX=g++-9
  - cmake --version
  - cmake CMakeLists.txt
  - cmake  --build .
