include(FetchContent)
FetchContent_Declare(
    googletest
    GIT_REPOSITORY https://github.com/google/googletest.git
    GIT_TAG        v1.15.2
)
set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(googletest)

add_executable(curiousx_test
    lexer_test.cpp
    parser_test.cpp
    sema_test.cpp
)

target_link_libraries(curiousx_test
    PRIVATE
        curiousx_core
        GTest::gtest_main
)

include(GoogleTest)
gtest_discover_tests(curiousx_test)
