name: Build and Deploy C++ WebAssembly

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: latest
          
      - name: Verify Emscripten Version
        run: emcc -v

      - name: Create Build Directory
        run: mkdir build

      - name: Configure and Build using CMake
        run: |
          cd build
          emcmake cmake ..
          cmake --build .

      # Test to ensure that the web assembly runs without any errors.
      - name: Test WebAssembly with emrun
        run: |
          emrun --no_browser --port 8080 web/index.html & # Start the server in the background
          sleep 10 # Wait to ensure the server starts
          kill %1 # Terminate the server process

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: web
